variables:
  VERSION_MAJOR: 0
  VERSION_MINOR: 0

trigger:
  - main
  - develop

resources:
  repositories:
    - repository: templates
      type: git
      name: devops-templates
extends:
  template: pipelines2/core-template.yml@templates
  parameters:
    VERSION_MAJOR: ${{ variables.VERSION_MAJOR }}
    VERSION_MINOR: ${{ variables.VERSION_MINOR }}
